# Generated by Django 5.0.6 on 2026-06-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_letter', models.TextField(blank=True)),
                ('ai_match_score', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('screening', 'AI Screening'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=12)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
